---
name: Release to Ansible Galaxy

"on":
  release:
    types: [ created, edited, published, released ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v7

      - name: Set up uv.
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies.
        run: uv sync --frozen

      - name: Trigger a new import on Galaxy.
        run: >
          uv run ansible-galaxy role import
          --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
          ${{ github.repository_owner }}
          ${{ github.event.repository.name }}
